backend:
  name: git-gateway
  branch: main # το branch στο GitHub
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Προϊόντα"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
